import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import ThemeProvider from "./_components/ThemeProvider";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages({ locale });
  return (
    <html lang={locale} className="snap-y snap-mandatory">
      <ThemeProvider>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}>
          <NextIntlClientProvider messages={messages}>
            {/* Apply ThemeWrapper here */}
            <main className="flex-1">{children}</main>
          </NextIntlClientProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
